channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - pyviz
dependencies:
  - zarr
  - jupyterlab
  - pytorch-lightning
  - python=3.9
  - pip=21.1
  - fire=0.4
  - cudatoolkit=11.3
  - pytorch=1.10
  # - torchvision=0.9.1
  - xarray
  - scikit-learn=0.24.2
  - numpy=1.20.2
  - netcdf4=1.5.6
  - matplotlib
  - holoviews
  - hvplot
  - bokeh
  - cartopy=0.19.0
  - tabulate=0.8.9
  - xrft=0.4.1
  - numpy_groupies=0.9.13
  - pip:
    - seaborn
    - sparse
    - omegaconf
    - einops
    - hydra-submitit-launcher
    - opencv-python==4.5.2.52
    - hydra-core
    - kornia
