channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - pip=21.0
  - cudatoolkit=10.2
  - pytorch=1.8
  - torchvision
  - xarray=0.17
  - scikit-learn
  - numpy
  - netcdf4
  - pip:
    - pytorch-lightning==1.3
    - hiplot
    - einops