file_paths:
  oi_4nadir: /gpfsstore/rech/yrf/commun/NATL60/NATL/oi/ssh_NATL60_4nadir.nc
  cal_data: /gpfswork/rech/yrf/commun/CalData/full_cal_obs.nc
  noisy_swot: /gpfswork/rech/yrf/commun/CalData/cal_data_karin_noise_only.nc
  natl_ssh: /gpfsstore/rech/yrf/commun/NATL60/NATL/ref/NATL60-CJM165_NATL_ssh_y2013.1y.nc
  natl_sst: /gpfsdsstore/projects/rech/yrf/commun/NATL60/NATL/ref/NATL60-CJM165_NATL_sst_y2013.1y.nc
  oi_swot_4nadir: /gpfsstore/rech/yrf/commun/NATL60/NATL/oi/ssh_NATL60_swot_4nadir.nc
  pseudo_obs: /gpfsstore/rech/yrf/commun/NATL60/NATL/data_new/dataset_nadir_0d_swot.nc
  new_noisy_swot: /gpfsssd/scratch/rech/yrf/ual82ir/sla-data-registry/CalData/cal_data_new_errs.nc
  new_noisy_swot_with_1d_decomp: /gpfsssd/scratch/rech/yrf/ual82ir/sla-data-registry/CalData/cal_data_new_syst_errs_20220218.nc
  natl_ssh_daily: /gpfsdsstore/projects/rech/yrf/commun/NATL60/NATL/ref_new/NATL60-CJM165_NATL_ssh_y2013.1y.nc
  natl_sst_daily: /gpfsdsstore/projects/rech/yrf/commun/NATL60/NATL/ref_new/NATL60-CJM165_NATL_sst_y2013.1y.nc
entrypoint:
  _target_: main.FourDVarNetRunner.train
  ckpt_path: null
  max_epochs: 200
  progress_bar_refresh_rate: 5
xp_name: aug0_dp200_5nad_map_no_sst_ng5x3cas
params:
  files_cfg:
    oi_path: /gpfsstore/rech/yrf/commun/NATL60/NATL/oi/ssh_NATL60_4nadir.nc
    oi_var: ssh_mod
    obs_mask_path: /gpfsssd/scratch/rech/yrf/ual82ir/sla-data-registry/CalData/cal_data_new_errs.nc
    obs_mask_var: five_nadirs
    obs_target_path: /gpfsssd/scratch/rech/yrf/ual82ir/sla-data-registry/CalData/cal_data_new_errs.nc
    obs_target_var: swot_no_noise
    gt_path: /gpfsstore/rech/yrf/commun/NATL60/NATL/ref/NATL60-CJM165_NATL_ssh_y2013.1y.nc
    gt_var: ssh
  iter_update:
  - 0
  - 20
  - 40
  - 60
  - 100
  - 150
  - 800
  nb_grad_update:
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  lr_update:
  - 0.001
  - 0.001
  - 0.001
  - 0.001
  - 0.001
  - 0.001
  - 0.001
  - 0.001
  - 0.001
  n_fourdvar_iter: 3
  weight_decay: 0.0
  model: 4dvarnet
  sst: false
  val_diag_freq: 5
  n_grad: 5
  dT: 5
  aug_state: false
  shape_data:
  - 15
  - 200
  - 200
  shape_state:
  - 15
  - 200
  - 200
  shape_obs:
  - 10
  dW: 3
  dW2: 1
  sS: 4
  stochastic: false
  animate: false
  UsePriodicBoundary: false
  nbBlocks: 1
  DimAE: 50
  dim_grad_solver: 150
  dropout: 0.1
  dropout_phi_r: 0.1
  alpha_mse_ssh: 1.0
  alpha_mse_gssh: 10.0
  alpha_loc_mse_ssh: 0.0
  alpha_loc_mse_gssh: 0.0
  loss_loc: 0
  alpha_proj: 0.5
  alpha_sr: 0.5
  alpha_lr: 0.5
  loss_glob: 1
  loss_proj: 1
  loss_low_res: 1
  automatic_optimization: true
  swot_anom_wrt: low_res
  anom_swath_init: zeros
  ckpt_name: modelCalSLAInterpGF-{epoch:02d}-{val_loss:.4f}
  norm_obs: l1
  norm_prior: l1
  patch_weight:
    _target_: calibration.lit_cal_model.get_constant_crop
    patch_size:
      lat: 200
      lon: 200
      time: 5
    crop:
      lat: 0
      lon: 0
      time: 2
  test_domain:
    lat:
      _target_: builtins.slice
      _args_:
      - 33.0
      - 43.0
    lon:
      _target_: builtins.slice
      _args_:
      - -65.0
      - -55.0
lit_mod_cls: calibration.lit_cal_model.LitCalModel
datamodule:
  _target_: calibration.dataset.FourDVarNetCalDataModule
  slice_win:
    lat: 200
    lon: 200
    time: 5
  strides:
    lat: 200
    lon: 200
    time: 1
  train_slices:
  - _target_: builtins.slice
    _args_:
    - '2013-02-04'
    - '2013-09-30'
  test_slices:
  - _target_: builtins.slice
    _args_:
    - '2012-10-20'
    - '2012-12-04'
  val_slices:
  - _target_: builtins.slice
    _args_:
    - '2013-01-01'
    - '2013-02-04'
  oi_path: /gpfsstore/rech/yrf/commun/NATL60/NATL/oi/ssh_NATL60_4nadir.nc
  oi_var: ssh_mod
  obs_target_path: /gpfsssd/scratch/rech/yrf/ual82ir/sla-data-registry/CalData/cal_data_new_errs.nc
  obs_target_var: swot_no_noise
  obs_mask_path: /gpfsssd/scratch/rech/yrf/ual82ir/sla-data-registry/CalData/cal_data_new_errs.nc
  obs_mask_var: five_nadirs
  gt_path: /gpfsstore/rech/yrf/commun/NATL60/NATL/ref/NATL60-CJM165_NATL_ssh_y2013.1y.nc
  gt_var: ssh
  sst_path: null
  sst_var: null
  dl_kwargs:
    batch_size: 2
    num_workers: 2
  item_prepro:
    _target_: calibration.dataset.weight_error
    w: 1.0
  dim_range:
    lat:
      _target_: builtins.slice
      _args_:
      - 33.0
      - 43.0
    lon:
      _target_: builtins.slice
      _args_:
      - -65.0
      - -55.0
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: .
  name: null
  default_hp_metric: false
seed: 0
dvc:
  entrypoint: hydra_main._main
  stage_name: run
  cmd: dvc stage add --force --name run python -c 'import dvc_main as dm; dm.dvc_execute()'
