# @package _global_
xp_name: siren_state
lit_mod_cls: calibration.implicit_solver.ImpLitCalMod
params:
  model: 4dsiren_sst
  shape_state:
    - 15
    - 240
    - 240
  siren_dim_hidden: 32
  siren_num_layers: 2

defaults:
  - /xp/xmasxp/base_xp
  - /splits/dc_boost_swot@datamodule
  - /xp/xmasxp/aug/without_aug_state
  - /xp/xmasxp/dl/d240_p240x5_s240x1
  - /xp/xmasxp/ds/clean_swot_oi_w_swot
  - /xp/xmasxp/sst/with_sst
  - /xp/xmasxp/loss/map
  - /xp/xmasxp/train_strat/dec_lr_ngrad5_15_nocas
  - _self_ 


