# @package _global_
xp_name: calmap_gf_dec_lr
datamodule:
  dl_kwargs:
    batch_size: 2
params:
  iter_update: [0, 10, 20, 30, 40, 150, 800]
  nb_grad_update: [5, 10, 10, 15, 15, 20, 20, 20]
  lr_update: [0.001, 0.001, 0.0001, 0.0001, 1.0e-05, 1.0e-05, 1.0e-06, 1.0e-07]
  n_grad: 5
  
defaults:
  - /legacy: fourdvarnet_calmap
  - /domain@datamodule.dim_range: gf
  - /training: calmap
  - _self_


