# @package _global_
xp_name: calmap_cascade_gf

patch_size:
  lat: 200
  lon: 200
  time: 5
strides:
  lat: 20
  lon: 20
  time: 1
datamodule:
  dl_kwargs:
    batch_size: 2
  slice_win: ${patch_size}
  strides: ${strides}
params:
  patch_weight:
    _target_: calibration.lit_cal_model.get_constant_crop
    patch_size: ${patch_size}
    crop: 
      lat: 20
      lon: 20
      time: 2
  test_domain: ???
  test_period: 
    _target_: builtins.slice
    _args_: ['2013-01-05', '2013-01-25']
  iter_update: [0, 2, 10, 30, 50, 100, 150, 800]
  nb_grad_update: [5, 5, 5, 5, 5, 5, 5, 5]
  lr_update: [0.001, 0.001, 0.001, 0.001, 1.0e-03, 1.0e-04, 1.0e-06, 1.0e-07]
  n_grad: 5
  n_fourdvar_iter: 3 
  rand_mask: false

defaults:
  - /params: fourdvarnet_calmap
  - /domain@datamodule.dim_range: gf_x
  - /domain@params.test_domain: gf
  - /training: calmap
  - _self_


