# @package _global_
xp_name: calmap_cascade_gf
datamodule:
  dl_kwargs:
    batch_size: 4
callbacks:
  - _target_: pytorch_lightning.callbacks.StochasticWeightAveraging
params:
  iter_update: [0, 2, 10, 30, 50, 100, 150, 800]
  nb_grad_update: [4, 4, 4, 4, 4, 4, 4, 4]
  lr_update: [0.001, 0.001, 0.001, 0.0005, 1.0e-04, 1.0e-04, 1.0e-06, 1.0e-07]
  n_grad: 4
  n_fourdvar_iter: 3 

defaults:
  - /params: fourdvarnet_calmap
  - /domain@datamodule.dim_range: gf
  - /training: calmap
  - _self_

