stages:
  run:
    cmd: PYTHONPATH=/raid/localscratch/qfebvre/4dvarnet-core python -m dvc_main.run
    deps:
    - /raid/localscratch/qfebvre/sla-data-registry/CalData/cal_data_new_errs.nc
    - /raid/localscratch/qfebvre/sla-data-registry/NATL60/NATL/oi/ssh_NATL60_4nadir.nc
    - /raid/localscratch/qfebvre/sla-data-registry/NATL60/NATL/ref/NATL60-CJM165_NATL_ssh_y2013.1y.nc
    params:
    - xp_config.yaml:
      - params.loss_loc
    outs:
    - dvc/checkpoints
    - dvc/outs
    metrics:
    - dvc/metrics:
        cache: false
