# @package _global_

xp_name: ${xp_name_obs}_${xp_name_cal}_${xp_name_sst}

defaults:
  - /xp/xmasxp/base_xp
  - /xp/xmasxp/aug/with_aug_state
  - /splits/dc_boost_swot@datamodule
  - /xp/xmasxp/dl/d240_p240x5_s240x1
  - /xp/xmasxp/train_strat/const_lr_ngrad_5_3cas
  - _self_ 

