# @package _global_

xp_name: james_240
patch_size:
  lat: 240
  lon: 240
  time: 5
strides:
  lat: 240
  lon: 240
  time: 1

datamodule:
  dl_kwargs:
    batch_size: 2
defaults:
  - /xp/james/base@_global_
  - _self_

