# @package _global_

xp_name: calmap_aug_ssh
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: .
  name: null
  default_hp_metric: False
params:
  loss_loc: 0
  alpha_mse_ssh: 1.0
  alpha_mse_gssh: 1.0
  alpha_loc_mse_ssh: 10.
  alpha_loc_mse_gssh: 10.
  model: 4dvarnet
  sst: false
  aug_state: true
  shape_state:
  - 20
  - 240
  - 240
file_paths:
  natl_ssh: '/gpfsstore/rech/yrf/commun/NATL60/NATL/ref_new/NATL60-CJM165_NATL_ssh_y2013.1y.nc'
  noisy_swot: '/gpfsstore/rech/yrf/commun/NATL60/NATL/data_new/dataset_nadir_0d_swot.nc'
defaults:
  - /xp/james/base@_global_
  - _self_
