# @package _global_

xp_name: calmap_aug
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: .
  name: null
  default_hp_metric: False
params:
  alpha_mse_ssh: 1.0
  alpha_mse_gssh: 1.0
  alpha_loc_mse_ssh: 10.
  alpha_loc_mse_gssh: 10.
  model: 4dvarnet
  sst: false
  aug_state: true
  shape_state:
  - 20
  - 240
  - 240
defaults:
  - /xp/james/base@_global_
  - _self_



