# @package _global_
xp_name: calmap_gf_icassp
datamodule:
  _target_: icassp_code_bis.new_dataloading.FourDVarNetDataModule
lit_mod_cls: icassp_code_bis.models.LitModel
defaults:
  - /legacy: icassp_fourdvarnet_calmap
  - /domain@datamodule.dim_range: gf
  - /training: calmap
  - _self_


