# @package _global_
xp_name: calmap_cascade_gf_swa
datamodule:
  dl_kwargs:
    batch_size: 2
callbacks:
  - _target_: pytorch_lightning.callbacks.StochasticWeightAveraging
params:
  iter_update: [0, 2, 10, 30, 50, 100, 150, 800]
  nb_grad_update: [5, 5, 5, 5, 5, 5, 5, 5]
  lr_update: [0.001, 0.001, 0.001, 0.001, 1.0e-03, 1.0e-04, 1.0e-06, 1.0e-07]
  n_grad: 5
  n_fourdvar_iter: 3 
  rand_mask: false

defaults:
  - /params: fourdvarnet_calmap
  - /domain@datamodule.dim_range: gf
  - /training: calmap
  - _self_


