# @package _global_
xp_name: finetune_calmap_gf_dec_lr
entrypoint:
  ckpt_path: "../calmap_gf_cascade/lightning_logs/version_2011266/checkpoints/modelCalSLAInterpGF-Exp3-epoch=42-val_loss=0.06.ckpt"
datamodule:
  dl_kwargs:
    batch_size: 2
params:
  iter_update: [0, 1, 10]
  nb_grad_update: [5, 5, 5, 5, 5, 5, 5, 5]
  lr_update: [0.001, 0.0005, 0.0001, 0.001, 1.0e-04, 1.0e-04, 1.0e-06, 1.0e-07]
  n_grad: 5
  n_fourdvar_iter: 3 
defaults:
  - /params: fourdvarnet_calmap
  - /domain@datamodule.dim_range: gf
  - /training: calmap
  - _self_

