# @package _global_

xp_name: map_aug_sst
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: .
  name: null
  default_hp_metric: False
datamodule:
  sst_path: ${file_paths.natl_sst}
  sst_var: sst
params:
  alpha_mse_ssh: 1.0
  alpha_mse_gssh: 10.0
  alpha_loc_mse_ssh: 0.
  alpha_loc_mse_gssh: 0.
  model: 4dvarnet_sst
  sst: true
  aug_state: true
  shape_state:
  - 20
  - 240
  - 240
defaults:
  - /xp/james/base@_global_
  - _self_


