# @package _global_

xp_name: map_augstate
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: .
  name: null
  default_hp_metric: False
params:
  loss_loc: 0
  ckpt_name: modelSLAInterpGF-Exp3-{epoch:02d}-{val_loss:.2f}
  alpha_mse_ssh: 1.0
  alpha_mse_gssh: 10.0
  alpha_loc_mse_ssh: 0
  alpha_loc_mse_gssh: 0
  model: 4dvarnet
  sst: false
  aug_state: true
  shape_state:
  - 20
  - 240
  - 240
defaults:
  - /xp/james/base@_global_
  - _self_
